name: Post Welcome Comment
on:
  pull_request:
    types: [opened]
jobs: 
  build:
    name: My Build Configuration
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Welcome!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: github.event.pull_request.html_url
